In [3]:
import numpy as np

from numpy.linalg import inv

from watermatrices import Amat, Bmat, yvec

In [35]:
size = Amat.shape[0]

E = np.vstack((np.hstack((Amat, Bmat)), np.hstack((Bmat, Amat))))

S = np.eye(size*2)
S[size:, size:] = -S[size:, size:]

z = np.hstack((yvec,-yvec))



In [41]:
# maxnorm is the maximum absolute row sum of the matrix.


maxnorm = lambda M: np.max(np.sum(np.abs(M), axis=1))

cond = lambda M: maxnorm(M) * maxnorm(inv(M))

print("Condition number of E: ", cond(E))

Condition number of E:  59.16590717093859


In [45]:
ωs = [0.800, 1.146, 1.400]

In [46]:
for ω in ωs:
    print("ω = ", ω)
    print("Condition number of E - ωS: ", cond(E-ω*S))

ω =  0.8
Condition number of E - ωS:  327.8167042420992
ω =  1.146
Condition number of E - ωS:  152679.26875233962
ω =  1.4
Condition number of E - ωS:  227.19443667104443


# LU Decomp

In [59]:
def pivot(M):
    M = M.copy()
    I = np.eye(M.shape[0])
    best = np.argmax(M[:,0])

    I[[0,best]] = I[[best,0]]

    return I@M


def decomp(M):
    M = M.copy()
    I = np.eye(M.shape[0])

    for i in range(M.shape[0]-1):
        M[i:,i:] = pivot(M[i:,i:])

        _I = I.copy()
        _I[i,(i+1):] = -M[i,(i+1):]/M[i,i]
        # wait does this work? 
        #apparanetly yes, thank you for asking


        M = M@_I
        #TODO: swap order
    return M

In [53]:
print(M)

print(pivot(M))

[[ 1  5  2  6]
 [11  9 24  2]
 [ 3 17 18  1]
 [ 2  5  7  1]]
[[11.  9. 24.  2.]
 [ 1.  5.  2.  6.]
 [ 3. 17. 18.  1.]
 [ 2.  5.  7.  1.]]


In [60]:
M = np.array([1, 5, 2, 6,11, 9, 24, 2, 3, 17, 18, 1, 2, 5, 7, 1])
M = M.reshape((4,4))

decomp(M).astype(int)

[[ 1  5  2  6]
 [11  9 24  2]
 [ 3 17 18  1]
 [ 2  5  7  1]]
I [[ 1. -5. -2. -6.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
I [[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.04347826 -1.39130435]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
I [[1.         0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         1.63669065]
 [0.         0.         0.         1.        ]]


array([[  1,   0,   0,   0],
       [ 11, -46,   0,   0],
       [  3,   2,  12,   0],
       [  2,  -5,   2,   0]])